[phases.setup]
nixpkgs = ["python3", "python3Packages.pip", "python3Packages.venv"]

[phases.install]
cmds = [
  "python3 -m venv /tmp/venv",
  "npm install",
  "/tmp/venv/bin/pip install -r requirements.txt"
]

[variables]
PATH = "/tmp/venv/bin:$PATH"
VIRTUAL_ENV = "/tmp/venv"

[start]
cmd = "node server.js"
